use crate::rules::*;
use crate::scan::ProjectContext;

// ═══════════════════════════════════════════════════════════════════
// R10: Mixed generated + handwritten code
// ═══════════════════════════════════════════════════════════════════

pub struct MixedGeneratedCode;

impl Rule for MixedGeneratedCode {
    fn id(&self) -> &str { "7.10" }
    fn name(&self) -> &str { "No mixed generated + handwritten files" }
    fn dimension(&self) -> Dimension { Dimension::ContextEfficiency }
    fn severity(&self) -> Severity { Severity::Low }

    fn check(&self, ctx: &ProjectContext) -> RuleResult {
        let gen_markers = ["@generated", "AUTO-GENERATED", "DO NOT EDIT",
            "Code generated by", "auto-generated", "THIS FILE IS GENERATED"];

        let mut mixed_files = Vec::new();
        let source = ctx.source_files();

        for f in source.iter().take(30) {
            let content = match std::fs::read_to_string(&f.path) {
                Ok(c) => c,
                Err(_) => continue,
            };
            if !gen_markers.iter().any(|m| content.contains(m)) { continue; }

            let total = content.lines().count();
            let marker_line = content.lines().enumerate()
                .filter(|(_, l)| gen_markers.iter().any(|m| l.contains(m)))
                .map(|(i, _)| i).last().unwrap_or(0);

            let after = total.saturating_sub(marker_line);
            if after as f64 / total.max(1) as f64 > 0.3 {
                mixed_files.push(f.relative_path.to_string_lossy().to_string());
            }
        }

        if mixed_files.is_empty() {
            self.pass()
        } else {
            self.warn(
                &format!("{} file(s) mix generated and handwritten code", mixed_files.len()),
                Suggestion {
                    priority: SuggestionPriority::NiceToHave,
                    title: "Separate generated from handwritten code".into(),
                    description: format!("Files: {}. Split so Claude doesn't edit generated sections.", mixed_files.join(", ")),
                    effort: Effort::Hour,
                },
            )
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
// R13: Claude memory directory
// ═══════════════════════════════════════════════════════════════════

pub struct MemoryDirectoryExists;

impl Rule for MemoryDirectoryExists {
    fn id(&self) -> &str { "7.11" }
    fn name(&self) -> &str { "Claude memory is being used" }
    fn dimension(&self) -> Dimension { Dimension::Foundation }
    fn severity(&self) -> Severity { Severity::Low }

    fn check(&self, ctx: &ProjectContext) -> RuleResult {
        let home = std::env::var("HOME").unwrap_or_default();
        let claude_dir = std::path::PathBuf::from(&home).join(".claude");
        let has_memory = claude_dir.join("projects").is_dir();

        let mentions_memory = ctx.claude_md_content.as_ref().map(|c| {
            let l = c.to_lowercase();
            l.contains("memory") || l.contains("remember") || l.contains("context")
        }).unwrap_or(false);

        if has_memory || mentions_memory {
            self.pass()
        } else {
            self.warn(
                "Claude memory system not detected",
                Suggestion {
                    priority: SuggestionPriority::NiceToHave,
                    title: "Use Claude's memory system".into(),
                    description: "Claude Code persists project context across sessions via memory. \
                        This saves ~2000 tokens/session by avoiding re-exploration. \
                        Memories are created automatically during Claude Code sessions.".into(),
                    effort: Effort::Minutes,
                },
            )
        }
    }
}
